Update Hub Install Instructions in OpenBCI_GUI.md
OpenBCI/Docs pull request #162
Opened 2019-01-19 17:14 UTC by retiutut

- [ ] Update text and example directories

- [ ] Update screenshots

2019-01-19 17:20 UTC, daniellasry commented
Hah! I was just beginning to work on this. Might have some screenshots for you.

2019-01-19 17:21 UTC, retiutut commented
I just fired up the Windows machine so I'll have it in a bit.

2019-01-19 17:24 UTC, retiutut commented
@daniellasry My Skype is the same as my name here: retiutut

2019-01-19 17:29 UTC, daniellasry commented
I'll add you shortly! I have to step away for a bit.

You can see my WIP here if you want to grab any of it (last 3 commits): https://github.com/daniellasry/Docs/commits/update-gui-windows-docs

I only took one screenshot so far, here: https://github.com/daniellasry/Docs/blob/fe8d2611e167ad92f2a7c9c7ddbb89976bb229b9/assets/images/gui_windows_drag_and_drop.png

2019-01-19 17:34 UTC, retiutut commented
Word! I like the window overlap to decrease the width of the image. Copying that style and just going to do two screenshots for the Hub location.

2019-01-19 17:55 UTC, retiutut commented
I updated just the one screenshot that is used twice.

https://github.com/OpenBCI/Docs/blob/3ab3c150667eb78896eaffbaf795a8754ae1ecc0/assets/images/gui_windows_drag_and_drop_hub.png

2019-01-19 17:59 UTC, retiutut commented
Done! 🔥

2019-01-19 21:01 UTC, daniellasry requested changes

2019-01-19 21:01 UTC, daniellasry commented on OpenBCI Software/01-OpenBCI_GUI.md
> +"\Processing\OpenBCI_GUI\data\OpenBCIHub\OpenBCIHub.exe"
There's no need to tell them to put the HUB in the data folder, since I already packaged the HUB with the latest GUI release. (as of 4.0.3)

2019-01-19 21:01 UTC, daniellasry commented on OpenBCI Software/01-OpenBCI_GUI.md
> +We recommend you leave the Hub running, even when not using the OpenBCI_GUI, the hub's impact on performance when not in use is minimal.
Since the HUB runs automatically from inside the GUI now, there's no need to leave the hub running

2019-01-19 21:08 UTC, daniellasry commented on OpenBCI Software/01-OpenBCI_GUI.md
> +"\Processing\OpenBCI_GUI\data\OpenBCIHub\OpenBCIHub.exe"
For that matter, the entire part where we tell them to install the HUB can be deleted. The Windows instructions should be pretty much the same as the Mac instructions, expect we need to tell them to check "run as admin" on the GUI, and to check the two boxes if they get prompted by the windows firewall.

2019-01-19 23:04 UTC, daniellasry commented on OpenBCI Software/01-OpenBCI_GUI.md
> +"\Processing\OpenBCI_GUI\data\OpenBCIHub\OpenBCIHub.exe"
By the way, I think I can contribute by adding commits to this PR. If that sounds good to you. I appreciate all your help, and don't want to give you more work!

2019-01-20 01:45 UTC, daniellasry commented
Pulled this into my PR #164 Thanks!

2019-01-20 01:45 UTC, closed without merging